apiVersion: v1
kind: Pod
metadata:
  name: goserver
  labels:
    name: goserver
spec:
  containers:
  - name: goserver
    image: nesrux/goserver
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
     - containerPort: 8000 
