apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
  #SECRET ta em BASE 64, caso tente em codificação normal (UTF -8)
  # Ele nao deixa eu injetar esse arquivo no kubernetes
  USER: cm9vdAo=
  PASS: cm9vdDEyMzQ1Ngo=
